s = input("Enter your Full Name: ")
print("Your Full Name is",s)
print(s[0:])	
print(s[:12])     
print(s[5:14])  
print(s[::-1])
print("a is at position",s.find("a"))
print("count of a is",s.count("a"))
print("Name in lowercase is",s.lower())
print("Name in uppercase is",s.upper())
print("Replacing 'a' by 'n'",s.replace("a","n"))
print("Name starts with 'a' is",s.startswith("A"))
print("Name ends with 'a' is",s.endswith("a"))
print("Name split at 'a' is",s.split("a")) 